services:
  # Web Service - Laravel Application
  - type: web
    name: sistem-penyimpanan-fail
    env: php
    plan: starter
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      npm install
      npm run build
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: |
      php artisan migrate --force
      php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_NAME
        value: "Sistem Penyimpanan Fail Tongod"
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: sistem-penyimpanan-fail-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: sistem-penyimpanan-fail-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: sistem-penyimpanan-fail-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: sistem-penyimpanan-fail-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: sistem-penyimpanan-fail-db
          property: password
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120
      - key: QUEUE_CONNECTION
        value: sync
    healthCheckPath: /
    regions:
      - singapore

  # Database Service - PostgreSQL
  - type: pserv
    name: sistem-penyimpanan-fail-db
    env: postgres
    plan: starter
    disk:
      name: sistem-penyimpanan-fail-db-disk
      mountPath: /var/lib/postgresql/data
      sizeGB: 10