services:
  - type: web
    name: sistem-penyimpanan-fail
    env: php
    plan: free
    buildCommand: |
      composer install --ignore-platform-reqs --no-dev
      php artisan key:generate || true
    startCommand: |
      php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_NAME
        value: "Sistem Penyimpanan Fail Tongod"
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: postgres.railway.internal
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        value: NvOz72WrYxgvbMafHFyELjMQtdQZIKLU