# Firebase Authentication Deployment Workflow with Token Auth
name: Deploy Firebase Auth with Token (Skip Login)

on:
  workflow_dispatch:
    inputs:
      skip_login:
        description: 'Skip interactive login'
        required: false
        default: 'true'
        type: boolean
      use_token:
        description: 'Use Firebase token authentication'
        required: false
        default: 'true'
        type: boolean
  push:
    branches:
      - main
    paths:
      - 'firebase-conversion/js/auth.js'
      - 'firebase-conversion/js/firebase-config.js'
      - 'firestore.rules'
      - 'firestore.indexes.json'

env:
  NODE_VERSION: '18'
  NPM_CONFIG_FUND: false
  NPM_CONFIG_AUDIT: false
  CI: true
  FIREBASE_CLI_EXPERIMENTS: webframeworks

jobs:
  deploy-auth:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          check-latest: true

      - name: Configure npm
        run: |
          npm config set fund false
          npm config set audit false
          npm config set progress false
          npm config set loglevel warn

      - name: Install dependencies
        run: |
          npm ci --no-fund --no-audit --prefer-offline
        env:
          NPM_CONFIG_FUND: false
          NPM_CONFIG_AUDIT: false

      - name: Install Firebase CLI globally
        run: |
          npm install -g firebase-tools
          firebase --version

      - name: Authenticate with Firebase using Service Account
        run: |
          echo "Setting up Firebase service account authentication..."
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SISTEM_PENYIMPANAN_FAIL_TONGOD }}' > $HOME/firebase-service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-service-account.json
          
          # Verify authentication
          firebase projects:list --json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-service-account.json

      - name: Deploy Firebase Authentication Rules
        run: |
          # Deploy Firestore rules
          firebase deploy --only firestore:rules --project sistem-penyimpanan-fail-tongod --non-interactive
          
          # Deploy Firestore indexes
          firebase deploy --only firestore:indexes --project sistem-penyimpanan-fail-tongod --non-interactive
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-service-account.json

      - name: Deploy Firebase Hosting with Auth
        run: |
          # Build the project
          npm run build
          
          # Deploy hosting with authentication configuration
          firebase deploy --only hosting --project sistem-penyimpanan-fail-tongod --non-interactive
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-service-account.json

      - name: Update Firebase Authentication Configuration
        run: |
          # Configure authentication providers
          echo "Updating Firebase Auth configuration..."
          
          # Enable Google provider (if not already enabled)
          firebase auth:import users.json --project sistem-penyimpanan-fail-tongod --hash-algo=scrypt --non-interactive || echo "No users to import"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-service-account.json

      - name: Verify deployment
        run: |
          echo "✅ Firebase Authentication deployment completed successfully"
          echo "🔑 Authentication method: Service Account Token"
          echo "🚫 Interactive login: Skipped"
          echo "🌐 Project: sistem-penyimpanan-fail-tongod"
          
          # Get hosting URL
          firebase hosting:sites:list --project sistem-penyimpanan-fail-tongod
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-service-account.json

      - name: Cleanup
        if: always()
        run: |
          # Remove service account file
          rm -f $HOME/firebase-service-account.json