# Fixed GitHub Actions workflow for Firebase Hosting deployment
name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
    paths:
      - 'firebase-conversion/**'
      - 'firebase.json'
      - 'firestore.rules'
      - 'firestore.indexes.json'
      - '.github/workflows/**'

env:
  NODE_VERSION: '18'
  NPM_CONFIG_FUND: false
  NPM_CONFIG_AUDIT: false
  CI: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          check-latest: true

      - name: Configure npm
        run: |
          npm config set fund false
          npm config set audit false
          npm config set progress false
          npm config set loglevel warn

      - name: Clean install dependencies
        run: |
          # Clean any existing node_modules and package-lock
          rm -rf node_modules package-lock.json
          
          # Install dependencies
          npm install --no-fund --no-audit --prefer-offline
        env:
          NPM_CONFIG_FUND: false
          NPM_CONFIG_AUDIT: false

      - name: Verify Firebase CLI
        run: |
          npx firebase --version
          npx firebase projects:list

      - name: Build project
        run: |
          # Create build directory
          mkdir -p dist
          
          # Copy firebase-conversion files to dist
          cp -r firebase-conversion/* dist/
          
          # Verify build output
          ls -la dist/
        env:
          NODE_ENV: production

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SISTEM_PENYIMPANAN_FAIL_TONGOD }}
          channelId: live
          projectId: sistem-penyimpanan-fail-tongod
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks